apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-92d6f77158f44b87
spec:
  capacity:
    storage: 1.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: backup-92d6f77158f44b87
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
