apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-bf49e0d486b2473c
spec:
  capacity:
    storage: 1.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: backup-bf49e0d486b2473c
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
