site_name: Homelab Documentation
plugins:
  - search
  - tags
  - awesome-pages
  - swagger-ui-tag
  - glightbox
  - gh-admonitions
theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo.drawio.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: slate
      primary: custom
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.top
    - toc.follow
repo_url: https://github.com/myles-coleman/homelab-cluster
edit_uri: edit/main/docs/
markdown_extensions:
  - admonition
  - pymdownx.details
  - markdown.extensions.md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: '#'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
extra_css:
  - assets/styles/extra.css
  - assets/styles/table.css
extra:
  generator: false
