apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Repository:
        - Github:
            - href: https://github.com/myles-coleman/homelab-cluster
  services.yaml: |
    - Downloaders:
        - Jellyseerr:
            icon: jellyseerr.svg
            href: https://jellyseerr.cowlab.org/
            description: Media Library Manager
        - Sonarr:
            icon: sonarr.svg
            href: https://sonarr.cowlab.org/
            description: TV Show Collection Manager
        - Radarr:
            icon: radarr.svg
            href: https://radarr.cowlab.org/
            description: Movie Collection Manager
        - Prowlarr:
            icon: prowlarr.svg
            href: https://prowlarr.cowlab.org/
            description: Indexer Collection Manager
        - Openbooks:
            icon: readarr.svg
            href: https://openbooks.cowlab.org/
            description: Search and Download eBooks

    - Media:
        - Jellyfin:
            icon: jellyfin.svg
            href: https://jellyfin.cowlab.org/
            description: Media Server
        - Calibre-Web:
            icon: calibre.svg
            href: https://calibre.cowlab.org/
            description: Browse and Read eBooks

    - Services:
        - Vaultwarden:
            icon: vaultwarden.svg
            href: https://vaultwarden.cowlab.org/
            description: Password Manager
        - Qbittorrent:
            icon: qbittorrent.svg
            href: https://qbittorrent.cowlab.org/
            description: Torrent Client
        - Copyparty:
            href: https://copyparty.cowlab.org/
            description: File Sharing and Management
        - Llama:
            href: https://chat.cowlab.org/
            description: AI Chat

    - System:
        - Pi-Hole:
            icon: pi-hole.svg
            href: https://pihole.cowlab.org/admin/login
            description: Network-Wide Ad Blocker
        - Pikvm:
            icon: pikvm.svg
            href: https://pikvm.cowlab.org/
            description: KVM Over IP
        - Argo CD:
            icon: argo-cd.svg
            href: https://argocd.cowlab.org/
            description: GitOps tool for Kubernetes
        - Longhorn:
            icon: longhorn.svg
            href: https://longhorn.cowlab.org/
            description: Distributed block storage
        - Nginx Proxy Manager:
            icon: nginx-proxy-manager.svg
            href: https://npm.cowlab.org/
            description: Proxy Server

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
    - datetime:
        text_size: xl
        format:
          timeStyle: short
    - search:
        provider: brave
        target: _blank
  docker.yaml: ""