apiVersion: v1
kind: Service
metadata:
  name: youtubedl-material
  namespace: youtubedl-material
spec:
  selector:
    app: youtubedl-material
  ports:
    - name: http
      protocol: TCP
      port: 17442
      targetPort: 17442
