apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: youtube
  namespace: youtubedl-material
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`youtube.cowlab.org`)
      kind: Rule
      services:
        - name: youtubedl-material
          port: 17442
