apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - video-pv.yaml
  - mongo-pvc.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - appdata-pvc.yaml
  - media-pvcs.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
