apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-audio
  namespace: youtubedl-material
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-video
  namespace: youtubedl-material
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs
  volumeName: ytdl-video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-subscriptions
  namespace: youtubedl-material
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-users
  namespace: youtubedl-material
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
