apiVersion: v1
kind: Service
metadata:
  name: ytdl-mongo-db
  namespace: youtubedl-material
spec:
  selector:
    app: ytdl-mongo-db
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
