apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
resources:
  - helm-chart.yaml
  - ingress.yaml
  - argo-ingress.yaml
  - namespace.yaml

components:
  - secrets/github
  - secrets/argocd

secretGenerator:
- name: dex-config
  files:
    - config.yaml
  options:
    disableNameSuffixHash: true