apiVersion: v1
kind: Service
metadata:
  name: fittrackee-db-hl
  namespace: fittrackee
spec:
  clusterIP: None
  selector:
    app: fittrackee-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
