apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fittrackee-secrets
  namespace: fittrackee
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: fittrackee-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: fittrackee
        POSTGRES_USER: fittrackee
        POSTGRES_PASSWORD: '{{ .FITTRACKEE_DB_PASSWORD }}'
        APP_SECRET_KEY: '{{ .FITTRACKEE_APP_SECRET_KEY }}'
        DATABASE_URL: 'postgresql://fittrackee:{{ .FITTRACKEE_DB_PASSWORD }}@fittrackee-db:5432/fittrackee'
  data:
  - secretKey: FITTRACKEE_DB_PASSWORD
    remoteRef:
      key: 417e19e6-6d9c-4cb3-ac18-77f2a3f992a4
  - secretKey: FITTRACKEE_APP_SECRET_KEY
    remoteRef:
      key: 62122a2f-9dce-4332-8507-781103b3e2dd
