apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fittrackee
  namespace: fittrackee
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fitness.cowlab.org`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: fittrackee
          port: 5000
