apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-6668a6f6c9794c0c
spec:
  capacity:
    storage: 1.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: backup-6668a6f6c9794c0c
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
