apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-1e0a71b480e741a4
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: backup-1e0a71b480e741a4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
