apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
  annotations:
    longhorn.io/volume-name: "backup-1e0a71b480e741a4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn
  volumeName: backup-1e0a71b480e741a4
