repositories:
- name: cloudflare
  url: https://cloudflare.github.io/helm-charts

releases:
- name: cloudflare-tunnel
  namespace: cloudflared
  chart: cloudflare/cloudflare-tunnel-remote
  version: 0.1.2
  values:
    - values.yaml
